import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
// import SignIn from "@/components/sign-in";
import UserAvatar from "@/components/UserAvatar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar>
          <UserAvatar />
        </Navbar>
        {children}
      </body>
    </html>
  );
}
